version: '3.8'
services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    image: rssscraper:0.1

  app:
    image: rssscraper:0.1
    ports:
      - "80:8000"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://rssapp:po6Ughai@db:5432/rssscraper
    depends_on:
      - db
      - build


  celery-worker:
    image: rssscraper:0.1
    command: celery  -A worker.celery worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      SQLALCHEMY_DATABASE_URI: postgresql://rssapp:po6Ughai@db:5432/rssscraper
    depends_on:
      - app
      - db
      - redis
      - build

  celery-beat:
    image: rssscraper:0.1
    command: celery  -A worker.celery beat
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      SQLALCHEMY_DATABASE_URI: postgresql://rssapp:po6Ughai@db:5432/rssscraper
    depends_on:
      - app
      - db
      - redis
      - build

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=rssapp
      - POSTGRES_PASSWORD=po6Ughai
      - POSTGRES_DB=rssscraper
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'



volumes:
  db:
    driver: local
